services:
  app_vet:
    build: DEPLOY-DOCKER
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://dpg-cvf2k39opnds73cp7md0-a:3306/prueba_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: prueba_jpa_user
      DB_PASSWORD: SYuAJHIdwtXKhMbe8cCQBucEaoj4M81Q
    restart: always
    depends_on:
      dpg-cvf2k39opnds73cp7md0-a:
        condition: service_healthy

  dpg-cvf2k39opnds73cp7md0-a:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SYuAJHIdwtXKhMbe8cCQBucEaoj4M81Q      
      MYSQL_PASSWORD: SYuAJHIdwtXKhMbe8cCQBucEaoj4M81Q
      MYSQL_DATABASE: prueba_jpa
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s