services:
  app_vet:
    build: DEPLOY-DOCKER
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://api.render.com/deploy/srv-cvf189nnoe9s73bbej00?key=hnN_Bj45DYk:3306/prueba_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      prueba_jpa:
        condition: service_healthy

  prueba_jpa:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234      
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: prueba_jpa
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s